[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/engine.py\", line 458, in run_steps",
      "    raw_result = recipe_obj.run_steps(api, engine)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/recipe_deps.py\", line 706, in run_steps",
      "    properties_def, api=api)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", line 89, in invoke_with_properties",
      "    arg_names, **additional_args)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", line 52, in _invoke_with_properties",
      "    return callable_obj(*props, **additional_args)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_modules/url/tests/validate_url.py\", line 13, in RunSteps",
      "    api.url.validate_url(api.properties['url_to_validate'])",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/recipe_api.py\", line 613, in _inner",
      "    return func(*a, **kw)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_modules/url/api.py\", line 126, in validate_url",
      "    raise ValueError('URL scheme must be either http:// or https://')",
      "ValueError: URL scheme must be either http:// or https://"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('URL scheme must be either http:// or https://',)"
    },
    "name": "$result"
  }
]