[
  {
    "failure": {
      "exception": {
        "traceback": [
          "<omitted by recipe engine>"
        ]
      },
      "humanReason": "Uncaught Exception: ValueError('URL must specify a network location.',)"
    },
    "name": "$result"
  }
]